### ISSUE TITLE
Some doubt about Equation(2) in your paper

### ISSUE THREAD

**Issue by Liu-Feng** [tianzheng4/PointCloud-Saliency-Maps#1]
Hi, sir. Thanks for opening this promising projects.
Before read your coder, I read your paper firstly. But I have some doubt about **Equation (2)** in your paper, which is about the gradient of loss to distance of a point to the spherical core(r). In my calculation, I got different reult with you according to the defination of r and (x,y,z). Can you give me a Email adress so that i can send my process of calculation to you.
I'm look forward to your reply and thank you very much.

**Comment by tianzheng4** [comment]
tzheng4@buffalo.edu
Thanks for your interest in our paper!!
Derivations are given in equation2_derive.jpg

**Comment by tianzheng4** [comment]
I just provided a more standard explanation in equation2_derive.jpg. Hope it can help you.
